export interface ErrorItem {
  id: string;
  message: string;
  category: "Interface" | "Process" | "Data Sync" | "Integration" | "Expression" | "Portal";
  cause: string;
  fix: string;
  docUrl?: string;
  tags: string[];
}

export const errorCategories = [
  "Interface",
  "Process",
  "Data Sync",
  "Integration",
  "Expression",
  "Portal",
] as const;

export const errors: ErrorItem[] = [
  // ===== INTERFACE / SAIL ERRORS =====
  {
    id: "E01",
    message: "Could not display interface. Please check definition and inputs.",
    category: "Interface",
    cause: "Runtime expression error in interface - null data, type mismatch, or missing rule input value. This is the most generic SAIL error and wraps a more specific underlying issue.",
    fix: "Check rule inputs aren't null. Add null guards with if(a!isNullOrEmpty(...)). Look at the full error message after 'Interface Definition:' for the specific expression that failed. Test each rule input independently.",
    docUrl: "https://docs.appian.com/suite/help/25.4/sail-best-practices.html",
    tags: ["interface", "null", "runtime", "common"],
  },
  {
    id: "E02",
    message: "Expression evaluation error at function [name]: Invalid types, can only act on data of the same type",
    category: "Interface",
    cause: "Type mismatch - comparing or operating on different data types (e.g. Any Type vs Integer, Text vs Number). Often occurs with wherecontains(), contains(), or comparison operators after querying data.",
    fix: "Cast data to matching types using tointeger(), tostring(), or todecimal(). When working with query results, use cast() to unwrap Any Type. Check that both sides of comparisons are the same type.",
    tags: ["type-mismatch", "cast", "any-type", "common"],
  },
  {
    id: "E03",
    message: "Target is Missing",
    category: "Expression",
    cause: "Missing comma somewhere in SAIL code. Since SAIL is a functional language, all code is function parameters separated by commas. A missing comma makes Appian think the next parameter is the 'target' of an assignment.",
    fix: "Find the missing comma. Check the line referenced in the error (if provided). Common locations: between function parameters, after closing parentheses, between items in a list {}.",
    tags: ["syntax", "comma", "common", "beginner"],
  },
  {
    id: "E04",
    message: "Invalid index: Cannot update integer index from type List of Null",
    category: "Interface",
    cause: "Trying to update a list item by index but the list is null or the wrong type. Common in editable grids when the local variable holding grid data hasn't been initialised.",
    fix: "Initialise your list variable before updating. Use a!localVariables with a default empty list of the correct CDT type: local!items: cast(typeof({recordType!MyRecord()}), {}). Ensure the index exists before updating.",
    tags: ["list", "null", "editable-grid", "index"],
  },
  {
    id: "E05",
    message: "An error occurred while executing a save",
    category: "Interface",
    cause: "A saveInto expression failed at runtime. Usually a type mismatch, null reference, or invalid operation inside the save. The full error message will contain the specific function and line that failed.",
    fix: "Debug with a!save(target: local!debug, value: save!value) to inspect what's being saved. Check types match between the value and target variable. Ensure any index operations inside saveInto reference valid positions.",
    tags: ["saveInto", "runtime", "common"],
  },
  {
    id: "E06",
    message: "Invalid function [name]",
    category: "Expression",
    cause: "Function doesn't exist in the current context. Could be: wrong Appian version, using an interface-only function in a process model (e.g. a!save()), typo in function name, or referencing a deleted expression rule.",
    fix: "Check function availability for your context. a!save() can't be used in process models. Some functions are interface-only. Verify the function exists in your Appian version's documentation.",
    tags: ["function", "context", "version"],
  },
  {
    id: "E07",
    message: "Expression evaluation error (no line number indicated)",
    category: "Expression",
    cause: "Error in a deeply nested expression where Appian can't determine the specific line. Can also occur when the error is in a referenced expression rule rather than the current one.",
    fix: "Use elimination: delete large code sections to isolate the error. If it disappears, undo and delete smaller sections within that block. Use a debug display component to inspect variable values at runtime.",
    tags: ["debugging", "nested", "no-line-number"],
  },
  {
    id: "E08",
    message: "Error Evaluating UI Expression",
    category: "Interface",
    cause: "Interface failed to render, usually due to a data issue rather than SAIL syntax. All data sources, queries, or integrations referenced in the interface may have returned unexpected types or null.",
    fix: "Check all data sources and queries are returning expected types. Verify rule inputs passed from process to interface. Test the interface independently with known-good test data.",
    tags: ["interface", "data", "rendering"],
  },

  // ===== PROCESS MODEL ERRORS =====
  {
    id: "E09",
    message: "Insufficient privileges to perform this action",
    category: "Process",
    cause: "The node runs in a user context that lacks permission to the referenced object. Every process node evaluates as a specific user - if that user can't access the record type, group, folder, or rule, this error fires.",
    fix: "Check object security on all referenced objects. Ensure the process initiator (or deployer for timer/subprocess) has necessary permissions. Use the Modify Process Security smart service if needed. Review the Alerts tab for who was notified.",
    docUrl: "https://docs.appian.com/suite/help/25.4/Testing_and_Debugging_Problems_with_Process_Models.html",
    tags: ["permissions", "security", "process", "common"],
  },
  {
    id: "E10",
    message: "The system has encountered an error. Details have been recorded.",
    category: "Process",
    cause: "Generic process error - a sub-process failed, an expression threw an unhandled exception, or there was an infrastructure issue. This is Appian's catch-all error message.",
    fix: "Go to Monitor view > Process Activity to find the specific failed node. Right-click the paused node to see the full error details. Check sub-processes for cascading failures.",
    docUrl: "https://docs.appian.com/suite/help/25.4/monitoring_view.html",
    tags: ["generic", "process", "monitor"],
  },
  {
    id: "E11",
    message: "Unable to complete task. Task has been cancelled.",
    category: "Process",
    cause: "The task was cancelled by another flow branch, a timer event, an escalation, or an administrator while the user was actively working on it. Common in processes with parallel flows or deadline timers.",
    fix: "Design processes to notify users before cancelling tasks. Add error handling to preserve the user's work. Consider using the 'Remove Assignments' approach instead of hard cancel. Show clear messages explaining why the task was cancelled.",
    tags: ["task", "cancelled", "UX", "parallel"],
  },
  {
    id: "E12",
    message: "Paused by exception",
    category: "Process",
    cause: "A node threw an unhandled runtime exception - expression evaluation error, data write failure, integration timeout, or null pointer. The process pauses at that node until an admin resolves it.",
    fix: "Check the paused node in Monitor view for the full error message. Right-click the node to restart it after fixing the issue. Consider adding exception flows to handle predictable errors gracefully.",
    docUrl: "https://docs.appian.com/suite/help/25.4/Testing_and_Debugging_Problems_with_Process_Models.html",
    tags: ["exception", "paused", "process", "common"],
  },
  {
    id: "E13",
    message: "A value exceeds the field's maximum length",
    category: "Process",
    cause: "Writing a string value that's longer than the database column allows. Common with Write Records or Write to Data Store Entity when user input isn't validated.",
    fix: "Add max length validation on form fields. Check CDT/column length definitions match expected input. Use the @Column JPA annotation with length attribute to control maximum characters.",
    tags: ["database", "write", "validation", "length"],
  },
  {
    id: "E14",
    message: "Process exceeded memory limit",
    category: "Process",
    cause: "Too much data loaded into process variables. Appian monitors memory usage per process and will error if a process consumes too much. Common when loading full record sets into process variables.",
    fix: "Reduce data fetched - use pagination and batch processing. Avoid loading entire tables into process variables. Use a!queryRecordType with appropriate batchSize and filters. Clear large process variables after use.",
    tags: ["memory", "performance", "process-variables"],
  },
  {
    id: "E15",
    message: "Problem saving process model (no further detail)",
    category: "Process",
    cause: "Invalid expression language somewhere in the process model. The expression designer validates slightly differently from the process model save validator. Stefan Helzle notes this gives no useful error message.",
    fix: "Check all expressions in all nodes - the error gives no line number. Disable nodes one by one to isolate the problem. Pay special attention to expressions in timer configurations, node inputs/outputs, and exception flows.",
    tags: ["save", "validation", "debugging", "stefan-helzle"],
  },

  // ===== DATA SYNC ERRORS =====
  {
    id: "E16",
    message: "Sync failed - record type exceeded the synced row limit (4 million rows)",
    category: "Data Sync",
    cause: "Record type source data exceeds 4 million rows. The sync will fail and record data becomes unavailable. Record types within 10% of the limit (3.6M-4M) will sync but show a warning.",
    fix: "Add sync filters to limit rows. Enable 'Keep data available at high volumes' to dynamically sync latest rows. Split large data sources into multiple record types. Consider whether all historical data needs to be synced.",
    docUrl: "https://docs.appian.com/suite/help/25.4/Records_Monitoring_Details.html",
    tags: ["sync", "row-limit", "4-million", "data-sync"],
  },
  {
    id: "E17",
    message: "Sync failed - duplicate values in a unique field",
    category: "Data Sync",
    cause: "A field configured as unique has duplicate values in the source data. This prevents the sync from completing.",
    fix: "Review and fix duplicate data in the source. If uniqueness isn't required, disable the unique constraint: Data Model > click field > deselect Unique Values > Save.",
    docUrl: "https://docs.appian.com/suite/help/25.4/Records_Monitoring_Details.html",
    tags: ["sync", "unique", "duplicate", "data-sync"],
  },
  {
    id: "E18",
    message: "Sync failed - full sync timeout (exceeded 4 hours)",
    category: "Data Sync",
    cause: "Full sync took longer than 4 hours to complete. More common with web service-backed record types. Record data becomes unavailable.",
    fix: "Remove the rate limit to speed up sync. Add a database index on the sort field. Allow larger batch sizes in the record data source. Add sync filters to reduce row count. For persistent timeout issues, consider disabling data sync.",
    docUrl: "https://docs.appian.com/suite/help/25.4/Records_Monitoring_Details.html",
    tags: ["sync", "timeout", "performance", "data-sync"],
  },
  {
    id: "E19",
    message: "Incremental sync failed - exceeded 50,000 rows or 10-minute limit",
    category: "Data Sync",
    cause: "An incremental sync tried to process more than 50,000 changed rows or took longer than 10 minutes. If 'Skip failed syncs' is not enabled, record data becomes unavailable.",
    fix: "Increase sync frequency so smaller batches are captured more regularly. Enable 'Skip failed full and incremental syncs' to keep data available. Enable recovery syncs to automatically trigger a full sync on failure.",
    docUrl: "https://docs.appian.com/suite/help/25.4/Records_Monitoring_Details.html",
    tags: ["sync", "incremental", "data-sync"],
  },
  {
    id: "E20",
    message: "Record data is unavailable",
    category: "Data Sync",
    cause: "A failed sync has made the record type's data inaccessible. All queries to this record type will fail, the record list is unavailable, and related record types may also be impacted.",
    fix: "Check Sync History for the specific error. Fix the underlying issue (permissions, source data, timeout). Perform a manual full sync. Enable 'Skip failed syncs' to prevent future data unavailability.",
    docUrl: "https://docs.appian.com/suite/help/25.4/Records_Monitoring_Details.html",
    tags: ["sync", "unavailable", "data-sync", "common"],
  },
  {
    id: "E21",
    message: "The record data does not exist, has been deleted, or you do not have sufficient privileges to access it",
    category: "Data Sync",
    cause: "Trying to access a record with an invalid ID, a deleted record, or the user lacks record-level security permissions. Also appears with entity-backed records using text primary keys.",
    fix: "Verify the record ID exists in the source data. Check record-level security configuration. For entity-backed records with text PKs, ensure the identifier format matches exactly.",
    tags: ["record", "security", "deleted", "permissions"],
  },

  // ===== INTEGRATION ERRORS =====
  {
    id: "E22",
    message: "Connection refused / Connection timed out",
    category: "Integration",
    cause: "The external service is unreachable from Appian's network. Could be wrong URL, firewall blocking the connection, service is down, or DNS resolution failure.",
    fix: "Verify the URL is correct and accessible. For Appian Cloud, ensure the external service allows Appian's IP ranges. Test connectivity from Appian's network. Check connected system configuration.",
    tags: ["connection", "timeout", "network", "common"],
  },
  {
    id: "E23",
    message: "HTTP 401 Unauthorized",
    category: "Integration",
    cause: "Authentication failed. OAuth token may have expired, API key is invalid, or credentials in the connected system are wrong.",
    fix: "Refresh the OAuth token in the connected system. Verify credentials are correct. Check if the API key has been rotated or revoked. For OAuth, ensure the refresh token is still valid.",
    tags: ["auth", "401", "oauth", "credentials"],
  },
  {
    id: "E24",
    message: "HTTP 403 Forbidden",
    category: "Integration",
    cause: "Authentication succeeded but the service account lacks permissions for the requested resource. The API key/token is valid but doesn't have the required scopes or roles.",
    fix: "Check API permissions and scopes on the external service. Verify the service account has access to the specific endpoint. Review OAuth scope configuration in the connected system.",
    tags: ["auth", "403", "permissions", "scopes"],
  },
  {
    id: "E25",
    message: "HTTP 429 Too Many Requests",
    category: "Integration",
    cause: "Rate limited by the external API. Appian is making too many requests in a given time window.",
    fix: "Add retry logic with exponential backoff. Reduce call frequency by caching results. Batch operations where possible. Check the API's rate limit headers for allowed request rates.",
    tags: ["rate-limit", "429", "throttling"],
  },
  {
    id: "E26",
    message: "Response size exceeds maximum allowed size",
    category: "Integration",
    cause: "Integration response body exceeds Appian's maximum allowed size (typically 10MB). Large API responses or file downloads can trigger this.",
    fix: "Add filters or pagination parameters to reduce response size. Request only specific fields if the API supports field selection. Break large requests into smaller batches.",
    tags: ["response-size", "10mb", "pagination"],
  },
  {
    id: "E27",
    message: "SSL handshake failed / Certificate error",
    category: "Integration",
    cause: "SSL/TLS certificate issue when connecting to an external service. The certificate may be self-signed, expired, or the certificate chain is incomplete.",
    fix: "For Appian Cloud, contact Appian Support to add the certificate to the truststore. For self-managed, import the certificate into Appian's Java truststore. Verify the certificate chain is complete.",
    tags: ["ssl", "certificate", "tls", "security"],
  },

  // ===== EXPRESSION GOTCHAS =====
  {
    id: "E28",
    message: "Data wrapped in Any Type causes comparison failures",
    category: "Expression",
    cause: "queryEntity() and some other functions return data wrapped in Any Type. Appian shows this as 'Any Type (Number (Integer))' instead of 'Number (Integer)'. Comparisons between wrapped and unwrapped types fail.",
    fix: "Use cast() to unwrap the data: cast(typeof(0), local!value). Better yet, use a!queryRecordType() which returns properly typed data. Avoid queryEntity() for new development.",
    tags: ["any-type", "cast", "queryEntity", "gotcha"],
  },
  {
    id: "E29",
    message: "Unexpected list count - lists of lists from a!forEach",
    category: "Expression",
    cause: "a!forEach() can create nested lists (list of lists) when curly braces {} are used inside the expression. Each iteration creates a list, and wrapping that in {} creates a list of lists.",
    fix: "Remove unnecessary curly braces {} inside a!forEach expressions. If you need a flat list, use a!flatten() as a last resort. Check with count() and typeof() to verify you have the expected structure.",
    tags: ["forEach", "list", "nested", "gotcha"],
  },
  {
    id: "E30",
    message: "Interface shows stale data after save operation",
    category: "Interface",
    cause: "After writing data to the database, the interface still shows old values because the local variable holding query results hasn't been refreshed.",
    fix: "Use a!refreshVariable with refreshOnVarChange to trigger a re-query after the save. Example: local!data: a!refreshVariable(value: rule!GetMyData(), refreshOnVarChange: local!saveCount). Increment local!saveCount in your saveInto.",
    tags: ["refresh", "stale-data", "saveInto", "common"],
  },

  // ===== PORTAL ERRORS =====
  {
    id: "E31",
    message: "Service Unavailable (Portal)",
    category: "Portal",
    cause: "Portal published but can't render due to expression errors in the interface. Similar to 'Could not display interface' but in the portal context where debugging is harder.",
    fix: "Check the portal object for validation errors. Review the Portal Errors grid on the Troubleshoot tab. Download Portal Error Log for detailed error messages. Test the interface independently in the interface designer first.",
    docUrl: "https://docs.appian.com/suite/help/25.4/portals-troubleshooting.html",
    tags: ["portal", "rendering", "service-unavailable"],
  },
  {
    id: "E32",
    message: "Using AI Skills across two different Appian sites in the same browser is not currently supported",
    category: "Portal",
    cause: "Browser session conflict when using AI Skills while logged into two different Appian environments in the same browser.",
    fix: "Use separate browsers or incognito/private windows for different Appian environments when using AI Skills.",
    docUrl: "https://docs.appian.com/suite/help/25.4/ai-troubleshooting.html",
    tags: ["ai-skills", "browser", "session"],
  },
];
